  <section id="footer">
    <p class="copyright">&#169; Mike Revitt <a id="CurrentYear"></a></p>
    <script>var d=new Date();document.getElementById("CurrentYear").innerHTML=d.getFullYear();</script>
    <p class="counter">No of distinct visitors
      <script type="text/javascript" src="//widget.supercounters.com/ssl/hit.js"></script>
      <script type="text/javascript">sc_hit(789773,14,6);</script>
    </p>
  </section> <!-- footer -->
