## about module for weewx skins
## Copyright Tom Keffer, Matthew Wall
## See LICENSE.txt for your rights
##
## Mike Revitt - Add visitor information
#errorCatcher Echo

<div id='visitors' class="widget">
    <div class="widget_title">
        <a href=http://s05.flagcounter.com/map/DXQp/size_xl/txt_000000/border_FFFFFF/pageviews_1/viewers_1/flags_1/>Visitors</a>
    </div>
    <div class="widget_contents">
        <p><img src="http://s05.flagcounter.com/count/DXQp/bg_FFFFFF/txt_000000/border_FFFFFF/columns_3/maxflags_50/viewers_3/labels_1/pageviews_1/flags_1/"></p>
    </div>
</div>
